version: '3.8'

services:
  # Stock Price Fetcher Microservice
  stock-price-fetcher-service:
    build:
      context: ./stock-price-fetcher-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - stockwatch-network

  # Stock Price Processor Microservice
  stock-price-processor-service:
    build:
      context: ./stock-price-processor-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - stockwatch-network

  # Alert Service Microservice
  alert-service:
    build:
      context: ./alert-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - stockwatch-network

  # User Preferences Service Microservice
  user-preferences-service:
    build:
      context: ./user-preferences-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - stockwatch-network

networks:
  stockwatch-network:
    driver: bridge
