version: '3.8'

services:
  analytics-service:
    build:
      context: ./analytics-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finstream-network

  ingestion-service:
    build:
      context: ./ingestion-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finstream-network

  reporting-service:
    build:
      context: ./reporting-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finstream-network

  storage-service:
    build:
      context: ./storage-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finstream-network

networks:
  finstream-network:
    driver: bridge
