spring:
  application:
    name: ingestion-service
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      retries: 0
      properties:
        linger.ms: 10
    consumer:
      group-id: finstream-group

  server:
    port: 8081

  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.security: WARN

kafka:
  topic:
    stock-data: stock-data-topic

finnhub:
  base-url: https://finnhub.io/api/v1
  key: your-api-key
